### ISSUE TITLE
Task 2.5 enabling TLS/SSL breaks frontend due to how the env var is used

### ISSUE THREAD

**Issue by benc-uk** [microsoft/aksworkshop#20]
2.5 doesn't currently seem 100% achievable due to the code of the frontend having `http://` hard coded into it.

I notice there's a open PR on the frontend to fix this https://github.com/Azure/azch-frontend/pull/1 but that's been open a while.

Is there something I've missed here?

**Comment by sabbour** [comment]
Yes you're right. Are you able to test your proposed solution (using `//` instead of a specific protocol)?

**Comment by benc-uk** [comment]
Hi, Yes I just tested this version (I created another PR sorry!)
https://github.com/Azure/azch-frontend/pull/2

Pushed it to Dockerhub https://hub.docker.com/r/bencuk/azch-frontend

And it worked ok

**Comment by sabbour** [comment]
Thanks for the fix.
