### ISSUE TITLE
2.2  Deploy MongoDB fails with doing helm init

### ISSUE THREAD

**Issue by ghstahl** [microsoft/aksworkshop#21]
1. I applied helm-rbac.yml  
2. MISTAKE:  just called helm init, should have called  "helm init --service-account tiller"  
3. FAILS: helm install stable/mongodb ....
4. tried to call: helm init --service-account tiller
5. STILL FAILS: helm install stable/mongodb ....

SOLUTION: thank goodness this was early in the workshop 
Created a new cluster and called; 

helm init --service-account tiller
SUCCESS: helm install stable/mongodb ....  

So is there a way to correct the helm init in the failing case?

**Comment by sabbour** [comment]
Most likely, you can do a [helm reset](https://github.com/helm/helm/blob/master/docs/helm/helm_reset.md).

**Comment by ghstahl** [comment]
you would think, but that subscription for the workshop doesn't let me
Something about the wrong privileges

H
