### ISSUE TITLE
too many certificates already issued for: nip.io: see https://letsencrypt.org/docs/rate-limits/

### ISSUE THREAD

**Issue by yuvagit** [microsoft/aksworkshop#29]
I am walk through the workshop and got the following error configuring the certificate. 

Here is the description of my frontend certificate. 

How do i resolve this issue?

Name:         frontend-tls-secret
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  certmanager.k8s.io/v1alpha1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2019-10-17T02:11:34Z
  Generation:          2
  Owner References:
    API Version:           extensions/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Ingress
    Name:                  frontend
    UID:                   c4d69bac-f5c0-4fbc-99e3-1cc7be0efd47
  Resource Version:        9060
  Self Link:               /apis/certmanager.k8s.io/v1alpha1/namespaces/default/certificates/frontend-tls-secret
  UID:                     44dcc8b3-a923-4df7-a18f-34a61a906b1f
Spec:
  Acme:
    Config:
      Domains:
        frontend.13.66.86.47.nip.io
      http01:
        Ingress:
  Dns Names:
    frontend.13.66.86.47.nip.io
  Issuer Ref:
    Kind:       ClusterIssuer
    Name:       letsencrypt
  Secret Name:  frontend-tls-secret
Status:
  Acme:
    Order:
      URL:
  Conditions:
    Last Transition Time:  2019-10-17T02:11:36Z
    Message:               Failed to create new order: acme: urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates already issued for: nip.io: see https://letsencrypt.org/docs/rate-limits/
    Reason:                ValidateError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason          Age                 From          Message
  ----     ------          ----                ----          -------
  Warning  ErrCreateOrder  11s (x33 over 30m)  cert-manager  Error creating order: acme: urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates already issued for: nip.io: see https://letsencrypt.org/docs/rate-limits/

**Comment by sabbour** [comment]
Unfortunately, we run into this every once in a while. Let's Encrypt issues a limited number of certificates for each domain and once this runs out, we have to wait again.
The workaround would be to use your own domain.

**Comment by shapeofarchitect** [comment]
How much time you had to wait - I guess they issue a new 50 certificate next week if following week was the one that had expired certs? Can you confirm ?

**Comment by sabbour** [comment]
Try to work around this by using a dashed IP in the domain, for example, 12-34-222-77.nio.io

**Comment by shapeofarchitect** [comment]
How does it matter to use - dash in the subdomains. For example I have abc.xyz as parent domain and I have subdomains foo.abc.xyz and bar.abc.xyz so in any case if I am not allowed to get any more certs for abc.xyz then there is no other way just to wait for next limits correct ?

**Comment by sabbour** [comment]
Let'sEncrypt treats the dashed notation as a subdomain of nip.io, try it and see if it works for you, and I've been told before that the dashed notation has different limits.

If you're still rate limited, try an alternative service from here https://moss.sh/free-wildcard-dns-services/

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
