### ISSUE TITLE
Certmanager version is too old

### ISSUE THREAD

**Issue by pelithne** [microsoft/aksworkshop#31]
The version of certmanager that is used in the instructions (--version v0.5.2) is no longer supported. The oldest version allowed is 0.8.0 

The instructions should be updated to use this new version, and to use the correct repository (stable/certmanager is not updated).

Suggested modification:

Change this:
````
helm install stable/cert-manager --name cert-manager --set ingressShim.defaultIssuerName=letsencrypt --set ingressShim.defaultIssuerKind=ClusterIssuer --version v0.5.2
````

To this:
````
# Install the CustomResourceDefinition resources separately
kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml

# Create the namespace for cert-manager 
kubectl create namespace cert-manager

# Add the Jetstack Helm repository
helm repo add jetstack https://charts.jetstack.io

# Update your local Helm chart repository cache
helm repo update

# Install the cert-manager Helm chart
helm install \
  --name cert-manager \
  --namespace cert-manager \
  --version v0.11.0 \
  jetstack/cert-manager
````

Also, the yaml definitions for the ingress controllers needs to be updated to reflect the new certmanager domain.

Change this
````
annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
````

To
````
annotations:
    cert-manager.io/cluster-issuer: letsencrypt
````

**Comment by sabbour** [comment]
Thanks a lot for reporting this! Do you want to open a pull request?

**Comment by pelithne** [comment]
Sure! Mid workshop right now, so it will take a little while :-)

**Comment by agrajm** [comment]
Funny I ran into the same issue today and just submitted a PR https://github.com/microsoft/aksworkshop/pull/33 to fix this
