### ISSUE TITLE
Loadbalancer needs to be explicitly defined as "basic"

### ISSUE THREAD

**Issue by pelithne** [microsoft/aksworkshop#32]
When using Azure Pass, users are not allowed to create a standard load balancer, but since standard is now the default (when creating the cluster with az aks create) you need to use the flag ````--load-balancer-sku```` and set it to basic.

Suggested change:

Change this
````
  az aks create --resource-group <resource-group> \
    --name <unique-aks-cluster-name> \
    --location <region> \
    --kubernetes-version $version \
    --generate-ssh-keys
````

To this
````
  az aks create --resource-group <resource-group> \
    --name <unique-aks-cluster-name> \
    --location <region> \
    --kubernetes-version $version \
    --generate-ssh-keys \´
    --load-balancer-sku basic 
````

**Comment by sabbour** [comment]
Added instructions in this commit https://github.com/microsoft/aksworkshop/commit/c3efd845c6d4620210a24e190b189f67d12583da
