### ISSUE TITLE
Azure Cloud Shell has Helm 3 - The lab doesn't support it yet

### ISSUE THREAD

**Issue by FokkoVeegens** [microsoft/aksworkshop#48]
As Azure Cloud Shell now comes with Helm 3, a lab participant cannot easily use this lab anymore. At least, the solutions are not valid for Helm 3. The main issues reside in the MongoDb install, Nginx-ingress install and the Cert-Manager install.

**Comment by sabbour** [comment]
Started working on the update https://github.com/sabbour/aksworkshop/pull/1

**Comment by snpdev** [comment]
@sabbour , not be a pain, but I am scheduled to deliver this workshop on Tuesday, Dec. 10th. Will the Helm 3 update be ready before then? I'll be happy to test your PR. Please let me know when you can. Thanks

**Comment by sabbour** [comment]
Merged. Should roll-out in a few minutes.

**Comment by pvandorp** [comment]
If I open Cloud Shell now it has Helm 2.16.3 configured. I cannot find instructions on how to upgrade. The AKS Workshop is targeted entirely to Cloud Shell with Helm 3

**Comment by sabbour** [comment]
My cloud shell shows running v3, I don't recall I've upgraded it.

```sh
ahmed@Azure:~$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

You may however want to follow the Helm 3 installation steps here https://helm.sh/docs/intro/install/#from-script
